---
# Handlers for nfs servers

- name: restart iptables
  service: name=iptables state=restarted

- name: restart nfs
  service: name={{ item }} state=restarted 
  with_items:
   - rpcbind
   - nfs
   - nfslock
