---
# plays common across all servers

- name: Disable SELinux in conf file
  lineinfile: dest=/etc/sysconfig/selinux regexp='^SELINUX=' line='SELINUX=disabled' state=present
  register: last_result

- name: Disable selinux dynamically
  shell: setenforce 0
  when: last_result.changed

- name: create the hosts entry for all servers
  template: src=hosts.j2 dest=/etc/hosts

- name: install the numa package
  yum: name=numactl state=installed

- name: create the user for sge operations
  user: name=sge password=$1$SomeSalt$ri7Ew.qbiP9MECdvQ69Vg0 uid=200 generate_ssh_key=yes

- name: Provide an authorized key for sge user
  authorized_key: user={{ sge_user }} key="{{ lookup('file','~/.ssh/id_rsa.pub') }}" state=present

