# this file defines behavior for the 'monitored_server' class of nodes

- name: install gmond
  yum: pkg=ganglia-gmond state=installed

- name: configure gmond
  template: src=../roles/ganglia/templates/etc/ganglia/gmond.conf dest=/etc/ganglia/gmond.conf owner=root group=root
  notify:
      - restart gmond

- name: ensure ganglia is running
  service: name=gmond state=running enabled=yes

