---
# This will install nagios

- name: create the nagios object files
  template: src={{ item + ".j2" }}
            dest=/etc/nagios/ansible-managed/{{ gname| default("petrol") }}-{{ hostvars[groups['clients'][0]].ansible_hostname }}-{{ item }}
  with_items:
    - sge_slave.cfg
  notify: restart nagios

- name: start nagios
  service: name=nagios state=started enabled=yes
