---
#Tasks for SGE master

- name: Copy the automated installation script
  template: src=inst_template.conf.j2 dest={{ sge_root_dir }}/uninstall_sge_template

- name: UNInstall the execution nodes
  shell: chdir={{ sge_root_dir }} ./inst_sge -ux -auto ./uninstall_sge_template
